export const MEALSDATA = [
  {
    id: "1",
    category: "BURGERS",
    name: "Veggie Burger",
    image: "/Images/veggie-burger.jpg",
  },
  {
    id: "2",
    category: "BURGERS",
    name: "Grilled Chicken Burger",
    image: "/Images/grilled-chicken-sandwich.jpg",
  },
  {
    id: "3",
    category: "PIZZAS",
    name: "Margherita Pizza",
    image: "/Images/margherita-pizza.jpg",
  },
  {
    id: "4",
    category: "DESERT",
    name: "Chocolate Brownie",
    image: "/Images/chocolate-brownie.jpg",
  },
  {
    id: "5",
    category: "DESERT",
    name: "Pancake Stack",
    image: "/Images/pancake-stack.jpg",
  },
  {
    id: "6",
    category: "DESERT",
    name: "Lemon Cheesecake",
    image: "/Images/lemon-cheesecake.jpg",
  },
  {
    id: "7",
    category: "PASTA",
    name: "Spaghetti Carbonara",
    image: "/Images/spaghetti-carbonara.jpg",
  },
//   {
//     id: "8",
//     category: "OTHERS",
//     name: "Beef Tacos",
//     image: "/Images/beef-tacos.png",
//   },
//   {
//     id: "9",
//     category: "OTHERS",
//     name: "Caesar Salad",
//     image: "/Images/caesar-salad.png",
//   },
//   {
//     id: "10",
//     category: "OTHERS",
//     name: "Chicken Curry",
//     image: "/Images/chicken-curry.png",
//   },
//   {
//     id: "11",
//     category: "OTHERS",
//     name: "Eggplant Parmesan",
//     image: "/Images/eggplant-parmesan.png",
//   },
//   {
//     id: "12",
//     category: "OTHERS",
//     name: "Falafel Wrap",
//     image: "/Images/falafel-wrap.png",
//   },
//   {
//     id: "13",
//     category: "OTHERS",
//     name: "Lobster Bisque",
//     image: "/Images/lobster-bisque.png",
//   },
//   {
//     id: "14",
//     category: "OTHERS",
//     name: "Mac & Cheese",
//     image: "/Images/mac-and-cheese.png",
//   },
//   {
//     id: "15",
//     category: "OTHERS",
//     name: "Miso Ramen",
//     image: "/Images/miso-ramen.png",
//   },
//   {
//     id: "16",
//     category: "OTHERS",
//     name: "Mushroom Risotto",
//     image: "/Images/mushroom-risotto.png",
//   },
//   {
//     id: "17",
//     category: "OTHERS",
//     name: "Seafood Paella",
//     image: "/Images/seafood-paella.png",
//   },
//   {
//     id: "18",
//     category: "OTHERS",
//     name: "Steak Frites",
//     image: "/Images/steak-frites.png",
//   },
//   {
//     id: "19",
//     category: "OTHERS",
//     name: "Sushi Roll Platter",
//     image: "/Images/sushi-roll-platter.png",
//   },
];
